name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build and test coverage
      run: npm run coverage

    - name: Publish to JFrog
      run: |
        # Hard-coding username and password
        echo "registry=http://20.123.51.156:8081/artifactory/api/npm/test-demo-npm-local" >> ~/.npmrc
        echo "//20.123.51.156:8081/artifactory/api/npm/test-demo-npm-local/:username=admin" >> ~/.npmrc
        echo "//20.123.51.156:8081/artifactory/api/npm/test-demo-npm-local/:_password=AP3Wynxi4VwC1hc9va8D3M73Cmi" >> ~/.npmrc
        npm publish
