name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build and test coverage
      run: npm run coverage

    - name: Publish to JFrog
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # Use a secret for your NPM token
      run: |
        echo "registry=http://20.123.51.156:8082/artifactory/api/npm/test-demo-npm-local" >> ~/.npmrc
        echo "//20.123.51.156:8082/artifactory/api/npm/test-demo-npm-local/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
        npm publish
