name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build and test coverage
      run: npm run coverage

    - name: Upload to JFrog
      uses: jfrog/setup-jfrog-cli@v2
      with:
        jfrog-cli-version: latest
        jfrog-cli-config: |
          {
            "artifactory": {
              "url": "http://20.123.51.156:8082",
              "user": "${{ secrets.JFROG_USER }}",
              "password": "${{ secrets.JFROG_PASSWORD }}"
            }
          }

    - name: Upload Coverage Reports
      run: |
        jfrog rt u "coverage/*" "General/test-npm-virual/coverage/" --recursive

    - name: Upload Application Code (optional)
      run: |
        jfrog rt u "app.js" "General/test-npm-virual/app/" --recursive
