name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build and test coverage
      run: npm run coverage

    - name: Configure npm for JFrog
      run: |
        echo "registry=http://20.123.51.156:8081/artifactory/api/npm/test-demo-npm-local/" >> ~/.npmrc
        echo "_auth=YWRtaW46QVAzV3lueXk0VndDY1hjOXZhOEQzTTczQ21j" >> ~/.npmrc
        echo "email=youremail@email.com" >> ~/.npmrc
        echo "always-auth=true" >> ~/.npmrc

    - name: Publish to JFrog
      run: npm publish
