name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build and test coverage
      run: npm run coverage

    - name: Publish to JFrog
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # Use a secret for your NPM token
      run: |
        npm config set registry http://20.123.51.156:8081/artifactory/api/npm/test-npm-virual/
        echo "//20.123.51.156:8081/artifactory/api/npm/test-npm-virual/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
        npm publish
