name: Deploy Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PM2
      run: npm install -g pm2

    - name: Install dependencies
      run: npm install

    - name: Stop application if running
      run: pm2 delete web-app || true

    - name: Run unit tests
      run: npm test

    - name: Run code coverage
      run: npm run coverage

    - name: Start application with PM2
      run: pm2 start npm --name "web-app" -- start

    - name: Wait for application to start
      run: sleep 10

    - name: Check PM2 processes
      run: pm2 list

    - name: Access application on browser
      run: curl -I http://localhost:3000
