  name: Deploy Application
  
  on:
    workflow_dispatch:
  
  jobs:
    unit-testing:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4     
        with:
            node-version: '20.x'
            
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  
      - name: Install dependencies
        run: npm install
  
      - name: Run unit tests
        run: npm test
  
      - name: Run code coverage
        run: npm run coverage
