name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PM2
      run: npm install -g pm2

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Run code coverage
      run: npm run coverage

    - name: Start application with PM2
      run: |
        pm2 start npm --name "your_app_name" -- start || pm2 restart "your_app_name"

    - name: Wait for application to start
      run:  sleep 10

    - name: Access application on browser
      run: curl -I http://localhost:3000
