name: Deploy Application

on:
  workflow_dispatch:

env:
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  
      - name: Install dependencies
        run: npm install
  
      - name: Run unit tests
        run: npm test

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: Mocha-test-result
          path: test-results.xml
          
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  
      - name: Install dependencies
        run: npm install
  
      - name: Run code coverage
        continue-on-error: true
        run: npm run coverage

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-result
          path: coverage
          retention-days: 5

  publish-build:
    runs-on: ubuntu-latest
    needs: code-coverage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .npmrc for JFrog Artifactory
        run: |
          echo "_auth = YWRtaW46QVA0U0Y3QUI0Q3ZvV0UyZXBUSEJZTjhodW9U" > ~/.npmrc
          echo "email = charanv@devtools.in" >> ~/.npmrc
          echo "always-auth = true" >> ~/.npmrc
          echo "registry = http://4.242.40.69:8081/artifactory/api/npm/test-npm-local/" >> ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Publish package to Artifactory
        run: npm publish

      - name: Upload code coverage to Artifactory
        run: npm publish coverage --registry=http://4.242.40.69:8081/artifactory/api/npm/test-npm-local/

      - name: Upload test results to Artifactory
        run: npm publish test-results.xml --registry=http://4.242.40.69:8081/artifactory/api/npm/test-npm-local/
